[project]
name = "faest-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest==9.0.1",
    "pytest-xdist>=3.8.0",
]